// frontend/components/chat/ChatWindow.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { Send, Wifi, WifiOff, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ChatMessage } from "./ChatMessage";
import { useWebSocket } from "@/hooks/useWebSocket";
import { cn } from "@/lib/utils";
import type { ApiKeys } from "@/types";

interface ChatWindowProps {
  ticker: string;
  keys: ApiKeys;
  initialSessionId?: string;
}

export function ChatWindow({ ticker, keys, initialSessionId }: ChatWindowProps) {
  const [input, setInput] = useState("");
  const bottomRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    const ta = textareaRef.current;
    if (!ta) return;
    ta.style.height = "auto";
    ta.style.height = `${Math.min(ta.scrollHeight, 200)}px`;
  }, [input]);

  // History loading is handled inside the hook — no callback needed here
  const { messages, status, sendMessage } = useWebSocket({
    ticker,
    keys,
    sessionId: initialSessionId,
  });

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  function handleSend() {
    const text = input.trim();
    if (!text || status !== "connected") return;
    sendMessage(text);
    setInput("");
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  }

  const statusColor = {
    connecting: "text-yellow-500",
    connected: "text-primary",
    disconnected: "text-muted-foreground",
    error: "text-destructive",
  }[status];

  const StatusIcon =
    status === "connecting" ? Loader2 : status === "connected" ? Wifi : WifiOff;

  return (
    <div className="flex h-full flex-col rounded-xl border border-border/60 bg-card overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border/60 px-4 py-3">
        <div className="flex items-center gap-2">
          <span className="font-display text-sm font-semibold">{ticker}</span>
          <span className="text-xs text-muted-foreground">AI Analyst</span>
        </div>
        <div className={cn("flex items-center gap-1.5 text-xs", statusColor)}>
          <StatusIcon
            className={cn("h-3.5 w-3.5", status === "connecting" && "animate-spin")}
          />
          <span className="capitalize">{status}</span>
        </div>
      </div>

      {/* Messages */}
      <ScrollArea className="flex-1 p-4">
        {messages.length === 0 ? (
          <div className="flex h-full flex-col items-center justify-center py-12 text-center">
            <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
              <Send className="h-5 w-5 text-primary" />
            </div>
            <p className="text-sm font-medium">Ask anything about {ticker}</p>
            <p className="mt-1 text-xs text-muted-foreground">
              Try: &quot;What are the main risks?&quot; or &quot;Summarize the latest 10-K&quot;
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {messages.map((msg) => (
              <ChatMessage key={msg.id} message={msg} />
            ))}
            <div ref={bottomRef} />
          </div>
        )}
      </ScrollArea>

      {/* Input */}
      <div className="border-t border-border/60 p-3">
        <div className="flex items-end gap-2 rounded-xl border border-border/60 bg-background px-3 py-2 focus-within:border-primary/50 focus-within:ring-1 focus-within:ring-primary/20">
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={
              status === "connected"
                ? "Ask about this company…"
                : status === "connecting"
                ? "Connecting…"
                : "Disconnected"
            }
            disabled={status !== "connected"}
            rows={1}
            className="flex-1 resize-none overflow-y-auto bg-transparent text-sm leading-5 outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed"
            style={{ maxHeight: "200px" }}
          />
          <Button
            size="icon"
            className="h-7 w-7 shrink-0 rounded-lg"
            disabled={!input.trim() || status !== "connected"}
            onClick={handleSend}
          >
            <Send className="h-3.5 w-3.5" />
          </Button>
        </div>
        <p className="mt-1.5 text-center text-[10px] text-muted-foreground">
          Enter to send · Shift+Enter for newline
        </p>
      </div>
    </div>
  );
}

// frontend/src/lib/components/ChatWindow.svelte
<script lang="ts">
  import { onMount, afterUpdate } from 'svelte';
  import ChatMessage from './ChatMessage.svelte';

  export let ticker: string;

  interface Message {
    role: 'user' | 'assistant';
    content: string;
  }

  let messages: Message[] = [];
  let input = '';
  let socket: WebSocket | null = null;
  let connected = false;
  let messagesContainer: HTMLElement;

  onMount(() => {
    connectWebSocket();
    return () => socket?.close();
  });

  afterUpdate(() => {
    if (messagesContainer) {
      messagesContainer.scrollTop = messagesContainer.scrollHeight;
    }
  });

  function connectWebSocket() {
    const wsUrl = `ws://localhost:8000/ws/chat/${ticker}`;
    socket = new WebSocket(wsUrl);

    socket.onopen = () => {
      connected = true;
      messages = [{
        role: 'assistant',
        content: `Connected. Ready to analyze ${ticker}.`
      }];
    };

    socket.onmessage = (event) => {
      const data = JSON.parse(event.data);
      messages = [...messages, {
        role: 'assistant',
        content: data.message
      }];
    };

    socket.onerror = () => {
      connected = false;
      messages = [...messages, {
        role: 'assistant',
        content: 'Connection error. Is the API running?'
      }];
    };

    socket.onclose = () => {
      connected = false;
    };
  }

  function sendMessage() {
    if (!input.trim() || !socket || !connected) return;

    messages = [...messages, {
      role: 'user',
      content: input
    }];

    socket.send(input);
    input = '';
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  }
</script>

<div class="chat-window">
  <div class="header">
    <div class="ticker-display">
      <span class="symbol">{ticker}</span>
      <span class="status {connected ? 'online' : 'offline'}">
        {connected ? 'LIVE' : 'OFFLINE'}
      </span>
    </div>
  </div>

  <div class="messages" bind:this={messagesContainer}>
    {#each messages as message}
      <ChatMessage role={message.role} content={message.content} />
    {/each}
  </div>

  <div class="input-area">
    <textarea
      bind:value={input}
      on:keydown={handleKeydown}
      placeholder="ask anything..."
      disabled={!connected}
      rows="3"
    />
    <button on:click={sendMessage} disabled={!connected || !input.trim()}>
      send
    </button>
  </div>
</div>

<style>
  .chat-window {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: var(--bg-darker);
    border: 1px solid var(--border);
    border-radius: 8px;
    overflow: hidden;
  }

  .header {
    padding: 1rem 1.5rem;
    background: var(--bg-card);
    border-bottom: 1px solid var(--border);
  }

  .ticker-display {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .symbol {
    font-size: 1.5rem;
    font-weight: 700;
    letter-spacing: 0.05em;
    color: var(--text);
  }

  .status {
    padding: 0.2rem 0.6rem;
    border-radius: 3px;
    font-size: 0.7rem;
    font-weight: 600;
    letter-spacing: 0.1em;
  }

  .status.online {
    background: rgba(0, 255, 157, 0.15);
    color: var(--success);
  }

  .status.offline {
    background: rgba(255, 51, 102, 0.15);
    color: var(--danger);
  }

  .messages {
    flex: 1;
    padding: 1.5rem;
    overflow-y: auto;
    min-height: 400px;
  }

  .input-area {
    padding: 1rem 1.5rem;
    background: var(--bg-card);
    border-top: 1px solid var(--border);
    display: flex;
    gap: 0.8rem;
  }

  textarea {
    flex: 1;
    background: var(--bg-input);
    border: 1px solid var(--border);
    border-radius: 4px;
    padding: 0.8rem;
    color: var(--text);
    font-family: inherit;
    font-size: 0.9rem;
    resize: none;
    transition: border-color 0.2s;
  }

  textarea:focus {
    outline: none;
    border-color: var(--accent);
  }

  textarea::placeholder {
    color: var(--text-muted);
  }

  textarea:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  button {
    background: var(--accent);
    color: var(--bg-dark);
    border: none;
    padding: 0.8rem 1.5rem;
    border-radius: 4px;
    font-size: 0.85rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    align-self: flex-end;
  }

  button:hover:not(:disabled) {
    background: var(--accent-dim);
    transform: translateY(-1px);
  }

  button:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }
</style>
